version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      aws:
        patterns:
          - "github.com/aws/aws-sdk-go*"
      test-dependencies:
        patterns:
          - "*test*"
          - "*mock*"
          
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
