package handlers

import (
	"errors"
	"sync"
	"time"
)

// MFA enrolment state (WP-R12-8, Review R12-23 / R5-15b).
//
// The TOTP secret a user is about to enrol is generated by the server and
// kept HERE until the user proves they hold it (a valid 6-digit code). It
// used to travel through the browser in a hidden form field and come back on
// the enable POST — so the "secret" enrolled was whatever the form said, and
// an account could be given a secret of the user's (or a script's) choosing.
//
// Where it lives: this process's memory, keyed by the dashboard session id,
// like the 2FA login challenge (dashboard.MFAPendingStore). Not PostgreSQL:
// a table of not-yet-confirmed TOTP secrets is one more place a secret is at
// rest, for state that lives ten minutes. The price is a restart: the box
// redeploys several times a day, and an enrolment that is open across one
// loses its pending secret — the enable POST then answers "scan the new QR
// code" and the page shows a fresh one (the authenticator keeps a stale
// entry the user has to remove). Never the alternative: enrolling a secret
// the server no longer holds.
//
// Bounds: one entry per session (a second tab or a reload gets the SAME
// secret), a 10-minute TTL from the first open, expired entries swept when
// the store reaches mfaEnrolSweepAt, and a hard cap (mfaEnrolMax) at which a
// new enrolment is refused rather than the map grown.

// MFAEnrolment is a generated TOTP secret waiting for its first valid code.
type MFAEnrolment struct {
	UserID     string
	Secret     string
	OTPAuthURL string
	Expires    time.Time
}

const (
	mfaEnrolTTL     = 10 * time.Minute
	mfaEnrolSweepAt = 256
	mfaEnrolMax     = 5000
)

// ErrMFAEnrolmentBusy: the store is full of live enrolments.
var ErrMFAEnrolmentBusy = errors.New("too many two-factor enrolments in progress")

// MFAEnrolResult is the outcome of confirming a pending enrolment.
type MFAEnrolResult int

const (
	// MFAEnrolNone: no pending secret for this session and user — it
	// expired, was used, or the process restarted since the page was opened.
	MFAEnrolNone MFAEnrolResult = iota
	// MFAEnrolMismatch: the code is not valid for the pending secret. The
	// entry is kept: the QR code the user scanned is still the right one.
	MFAEnrolMismatch
	// MFAEnrolOK: the code verified; the entry was taken (single use).
	MFAEnrolOK
)

// MFAEnrolmentStore holds pending enrolments by session id.
type MFAEnrolmentStore struct {
	mu      sync.Mutex
	entries map[string]MFAEnrolment
	ttl     time.Duration
	max     int
	now     func() time.Time
}

// NewMFAEnrolmentStore creates an empty store.
func NewMFAEnrolmentStore() *MFAEnrolmentStore {
	return &MFAEnrolmentStore{entries: make(map[string]MFAEnrolment), ttl: mfaEnrolTTL, max: mfaEnrolMax, now: time.Now}
}

// Begin returns the pending enrolment of (session, user), generating one
// with gen when there is none, it expired, or the session id is presented by
// another user than the one it was created for.
func (s *MFAEnrolmentStore) Begin(sessionID, userID string, gen func() (secret, otpauthURL string, err error)) (MFAEnrolment, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	now := s.now()
	if e, ok := s.entries[sessionID]; ok && e.UserID == userID && now.Before(e.Expires) {
		return e, nil
	}
	delete(s.entries, sessionID)
	if len(s.entries) >= mfaEnrolSweepAt || len(s.entries) >= s.max {
		for k, e := range s.entries {
			if !now.Before(e.Expires) {
				delete(s.entries, k)
			}
		}
	}
	if len(s.entries) >= s.max {
		return MFAEnrolment{}, ErrMFAEnrolmentBusy
	}
	secret, otpauthURL, err := gen()
	if err != nil {
		return MFAEnrolment{}, err
	}
	e := MFAEnrolment{UserID: userID, Secret: secret, OTPAuthURL: otpauthURL, Expires: now.Add(s.ttl)}
	s.entries[sessionID] = e
	return e, nil
}

// Peek returns the live pending enrolment of (session, user) without taking it.
func (s *MFAEnrolmentStore) Peek(sessionID, userID string) (MFAEnrolment, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	e, ok := s.entries[sessionID]
	if !ok || e.UserID != userID || !s.now().Before(e.Expires) {
		return MFAEnrolment{}, false
	}
	return e, true
}

// Confirm checks a code against the pending secret under the store's lock:
// verify is called with the secret; when it returns true the entry is taken
// (two tabs posting at once cannot both enrol). A wrong code keeps the entry.
func (s *MFAEnrolmentStore) Confirm(sessionID, userID string, verify func(secret string) bool) (MFAEnrolment, MFAEnrolResult) {
	s.mu.Lock()
	defer s.mu.Unlock()
	e, ok := s.entries[sessionID]
	if !ok || e.UserID != userID || !s.now().Before(e.Expires) {
		if ok && e.UserID == userID {
			delete(s.entries, sessionID) // expired
		}
		return MFAEnrolment{}, MFAEnrolNone
	}
	if !verify(e.Secret) {
		return MFAEnrolment{}, MFAEnrolMismatch
	}
	delete(s.entries, sessionID)
	return e, MFAEnrolOK
}

// Restore puts back an enrolment Confirm took, for the case where enabling
// failed afterwards (the database refused the write): the user's QR code is
// still good and the next attempt can succeed.
func (s *MFAEnrolmentStore) Restore(sessionID string, e MFAEnrolment) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, taken := s.entries[sessionID]; !taken && s.now().Before(e.Expires) {
		s.entries[sessionID] = e
	}
}

// Len returns the number of entries held (expired ones included until swept).
func (s *MFAEnrolmentStore) Len() int {
	s.mu.Lock()
	defer s.mu.Unlock()
	return len(s.entries)
}
