package dashboard

import (
	"regexp"
	"strings"
	"testing"

	"github.com/FairForge/vaultaire/internal/api/landing"
	"github.com/stretchr/testify/require"
)

// templates/generated/house.html (the house's sprite defs, room background
// and CSS for the overview page) is GENERATED by internal/api/landing/build.py
// from the same sources as the landing page (make landing). The stamp is the
// landing sources' sha256, so one rebuild keeps both outputs current and a
// hand edit to either fails CI.
func TestHouseTemplate_GeneratedFromLandingSources(t *testing.T) {
	src, err := Templates.ReadFile("templates/generated/house.html")
	require.NoError(t, err, "templates/generated/house.html is missing; run `make landing`")

	stamp := regexp.MustCompile(`sources sha256:([0-9a-f]{64})`).FindStringSubmatch(string(src))
	require.Len(t, stamp, 2, "generated/house.html must carry the generator's sha256 stamp; run `make landing`")

	got, err := landing.SourcesHash("../api/landing")
	require.NoError(t, err)
	require.Equal(t, stamp[1], got,
		"internal/api/landing/ sources changed but templates/generated/house.html was not rebuilt (or was edited by hand); run `make landing`")

	for _, def := range []string{`{{define "house-sprites"}}`, `{{define "house-css"}}`, `{{define "house-room"}}`} {
		require.True(t, strings.Contains(string(src), def), "missing %s", def)
	}
	for _, id := range []string{`id="s-box"`, `id="s-dresser"`, `id="s-bookcase"`, `id="s-lamp"`, `id="s-mascot-wave"`, `id="nightdim"`, `id="vig"`, `id="wallgrad"`} {
		require.True(t, strings.Contains(string(src), id), "missing %s", id)
	}
}
