name: Security
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: securego/gosec@master
      with:
        args: ./...
