name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run core tests
      run: |
        go test ./internal/api -short
        go test ./internal/auth -short
        go test ./internal/cache -short
        go test ./internal/gateway -short
        go test ./internal/billing -short
        go test ./internal/storage -short
        go test ./internal/tenant -short

    - name: Run driver tests (allow failures)
      run: |
        go test ./internal/drivers -short -skip TestRetryPolicy || true
        go test ./internal/engine -short || true
